newTable = {}
table.insert(newTable,"first")
table.insert(newTable,"second")
table.insert(newTable,"third")
print(newTable[1])
print(newTable[2])
table.insert(newTable,2,"fourth")
print(newTable[2])
table.remove(newTable,1)
print("+++++++++++++++++++++++++++++")
print(newTable[1])
print(newTable[2])
print(newTable[3])
print(newTable[4])

